openapi: 3.0.1
info:
  title: Microservice JAVA API
  description: Microservice JAVA API
  version: 1.0.1
servers:
- url: http://localhost:9090/api/v1/payment
security:
- SubscriptionKey: []
tags:
- name: API  Payment
  description: API  Payment
paths:
  /check/messages/{messageId}:
    get:
      tags:
      - API  Payment
      summary: Check Payment Message Update By MessageId
      operationId: getMessagePayment
      parameters:
      - name: messageId
        in: path
        description: payment's messageId
        required: true
        schema:
          type: string
      responses:
        200:
          description: check if the message has been paid
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiPaymentMessage'
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ApiPaymentMessage'
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Problem'
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Problem'
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
        404:
          description: Not Found
          content: {}
        503:
          description: Service Unavailable
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Problem'
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
components:
  schemas:
    ApiPaymentMessage:
      required:
      - fiscalCode
      - messageId
      - noticeNumber
      - paid
      type: object
      properties:
        messageId:
          minLength: 1
          type: string
        paid:
          type: boolean
          default: false
        dueDate:
          type: string
          format: date
        amount:
          type: number
          format: double
        fiscalCode:
          minLength: 1
          type: string
        noticeNumber:
          minLength: 1
          type: string
    Problem:
      type: object
      properties:
        error:
          type: string
          description: |
            error description.
          format: uri
        path:
          type: string
          description: |
            An absolute URI that identifies the specific occurrence of the problem. It may or may not yield further information if dereferenced.
        status:
          type: string
          description: |
            Status code description.
        timestamp:
          type: number
          description: |
            timestamp of the error
  securitySchemes:
    SubscriptionKey:
      type: apiKey
      description: The API key to access this function app.
      name: Ocp-Apim-Subscription-Key
      in: header
