oa3_spec: openapi/index.yaml
name: opex_fnservices_index
location: West Europe
timespan: 10m
evaluation_frequency: 5
evaluation_time_window: 30
event_occurrences: 3
data_source: /subscriptions/ec285037-c673-4f58-b594-d7c480da4e8b/resourceGroups/io-p-rg-external/providers/Microsoft.Network/applicationGateways/io-p-appgateway
action_groups:
  - /subscriptions/ec285037-c673-4f58-b594-d7c480da4e8b/resourceGroups/io-p-rg-common/providers/Microsoft.Insights/actiongroups/iopquarantineerror
overrides:
  hosts:
    - api.io.pagopa.it
    - api.io.italia.it
    - api-mtls.io.pagopa.it
  endpoints:
    /api/v1/services:
      response_time_threshold: 6
      availability_threshold: 0.95
    /api/v1/services/{service_id}:
      response_time_threshold: 6
      availability_threshold: 0.95
    /api/v1/services/{service_id}/logo:
      response_time_threshold: 6
      availability_threshold: 0.95
    /api/v1/subscriptions-feed/{date}:
      response_time_threshold: 3
