version: "3.2"

services:

  functions-node-14:
    image: functions-node-14
    build:
      context: ..
      dockerfile: ./docker/functions-node-14/Dockerfile
    command: /bin/true

  azure-cosmosdb-linux-emulator:
    image: mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator:latest
    container_name: azure-cosmosdb-linux-emulator
    hostname: "azure-cosmosdb-linux-emulator"
    tty: true
    mem_limit: 12GB
    cpu_count: 6
    ports:
      - 8081:8081
      - 10251:10251
      - 10252:10252
      - 10253:10253
      - 10254:10254
    environment:
      - AZURE_COSMOS_EMULATOR_PARTITION_COUNT=10
      - AZURE_COSMOS_EMULATOR_ENABLE_DATA_PERSISTENCE=true
      - AZURE_COSMOS_EMULATOR_IP_ADDRESS_OVERRIDE=127.0.0.1

  storage-account:
    image: azurite
    build:
      context: ../docker/azurite
      dockerfile: ./Dockerfile
    ports:
      - 10000:10000
      - 10001:10001
      - 10002:10002

  fixtures:
    image: fixtures
    container_name: fixtures
    env_file:
      - ./environments/generated/env.io-fixtures
    build:
      context: ../docker/fixtures
      dockerfile: ./Dockerfile
    links:
      - storage-account
      - azure-cosmosdb-linux-emulator

  function:
    image: fn
    env_file:
      - ./environments/generated/env.io-functions-services
    build:
      context: ..
      dockerfile: ./docker/functions/Dockerfile
    ports:
      - ${FUNCTIONS_SERVICES_PORT}:7071
    links:
      - azure-cosmosdb-linux-emulator
      - storage-account
    depends_on:
      - functions-node-14
      - fixtures

  testagent:
    image: node:16-alpine
    working_dir: /usr/src/app
    command: tail -f /dev/null # to keep it   up&running
    env_file:
      - environments/generated/env.integration-tests
    volumes:
      - "./:/usr/src/app"
      - "../openapi:/usr/src/openapi"
    depends_on:
      - azure-cosmosdb-linux-emulator
      - storage-account
      - fixtures
    links:
      - function
