name: Release Infrastructure

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - "infra/bootstrapper/**"

jobs:
  infra_release:
    uses: pagopa/dx/.github/workflows/infra_apply.yaml@main
    name: Release Infrastructure
    secrets: inherit
    with:
      environment: prod
      base_path: infra/bootstrapper
      use_private_agent: false