name: Release Infrastructure

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - "infra/resources/**"

jobs:
  infra_release:
    uses: pagopa/dx/.github/workflows/infra_apply.yaml@36ff122137235d814f3dbd20068acfb521d3fd74 # main
    name: Release Infrastructure
    secrets: inherit
    with:
      environment: prod
      base_path: infra/resources
      override_github_environment: infra-prod
      use_private_agent: true
