name: Release Infrastructure

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - "infra/resources/**"

jobs:
  infra_release:
    uses: pagopa/dx/.github/workflows/infra_apply.yaml@625f02f382c33eb449cd94facb8e426bf7ae37ea # main
    name: Release Infrastructure
    secrets: inherit
    with:
      environment: prod
      base_path: infra/resources
      override_github_environment: infra-prod
      use_private_agent: true
