name: Opex Dashboard function services index

# Controls when the workflow will run
on:
  push:
    branches:
      - master
      # - opex-demo
    paths:
      - "index.yaml"
      - ".github/workflows/opex_index.yml"
      - ".opex/index/**"

env:
  CLIENT_ID: 6e4bde28-ef8b-489d-bd1d-ce22d4aabfe6
  TENANT_ID: 7788edaf-0346-4068-9d79-c868aed15b3d
  SUBSCRIPTION_ID: ec285037-c673-4f58-b594-d7c480da4e8b
  API_NAME: index

permissions:
  id-token: write
  contents: read

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        environment: [prod]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        id: checkout
        # from https://github.com/actions/checkout/commits/main
        uses: actions/checkout@1f9a0c22da41e6ebfa534300ef656657ea2c6707
        with:
          persist-credentials: false
          fetch-depth: 0

      # from https://github.com/pagopa/opex-dashboard-azure-action/
      - uses: pagopa/opex-dashboard-azure-action@v1.1.0
        with:
          environment: ${{ matrix.environment }}
          api-name: ${{ env.API_NAME }}
          config: .opex/${{ env.API_NAME }}/env/${{ matrix.environment }}/config.yaml
          client-id: ${{ env.CLIENT_ID }}
          tenant-id: ${{ env.TENANT_ID }}
          subscription-id: ${{ env.SUBSCRIPTION_ID }}
          # from https://github.com/pagopa/opex-dashboard-azure-action/pkgs/container/opex-dashboard-azure-action
          docker-version: sha256:7e454c1892b2aaf3717782c07a2fa01504db5cc7d07979fae863dfc00a9f0173
